name: Deploy React App

on:
  push:
    branches: [ main ]  # Trigger on pushes to the 'main' branch (or your desired branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu virtual machines

    steps:
      - uses: actions/checkout@v3  # Checkout your code repository

      - name: Use Node.js 16  # Install the appropriate Node.js version (adjust if needed)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Remove Existing Node Modules
        run: npm run clean
        
      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build  # Replace with your build command, if different

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          local_dir: build  # Path to your production-ready build folder (adjust if needed)
          public_dir: build  # Configure the root of your deployed site (adjust if needed)
          branch: gh-pages  # Deploy to the 'gh-pages' branch (or your desired branch)
